// src/app/api/mint/prepare/route.ts
export const runtime = "nodejs";

import { NextResponse } from "next/server";
import { Uploader } from "@irys/upload";
import { BaseEth } from "@irys/upload-ethereum";

function mustEnv(name: string) {
  const v = process.env[name];
  if (!v) throw new Error(`Missing env var: ${name}`);
  return v;
}

type PrepareBody = {
  fid: number;
  username?: string; // ✅ NEW (optional)
};

function gatewaysFor(id: string) {
  return {
    irysGateway: `https://gateway.irys.xyz/${id}`,
    irysNode1: `https://node1.irys.xyz/${id}`,
    irysNode2: `https://node2.irys.xyz/${id}`,
    arweaveNet: `https://arweave.net/${id}`,
    arIo: `https://ar-io.dev/${id}`,
  };
}

// Normalize anything numeric-ish to bigint
function toBigInt(v: any): bigint {
  if (typeof v === "bigint") return v;
  if (typeof v === "number") return BigInt(Math.floor(v));
  if (typeof v === "string") return BigInt(v);
  if (v && typeof v.toString === "function") return BigInt(v.toString());
  throw new Error(`Unable to convert to bigint: ${String(v)}`);
}

// Handle SDK differences (getter vs function)
async function readIrysAddress(irys: any): Promise<string> {
  const a = irys.address;
  return typeof a === "function" ? String(await a.call(irys)) : String(a);
}

async function readLoadedBalance(irys: any): Promise<bigint> {
  const fn = irys.getLoadedBalance;
  if (typeof fn === "function") return toBigInt(await fn.call(irys));
  return toBigInt(irys.loadedBalance ?? irys.balance);
}

export async function POST(req: Request) {
  try {
    const body = (await req.json()) as PrepareBody;
    const fid = Number(body?.fid);
    const username =
      typeof body?.username === "string" && body.username.trim()
        ? body.username.trim()
        : undefined;

    if (!Number.isFinite(fid) || fid <= 0) {
      return NextResponse.json(
        { error: "Missing or invalid fid" },
        { status: 400 }
      );
    }

    // 1) Fetch PNG from existing generator
    const base =
      process.env.NEXT_PUBLIC_URL &&
      process.env.NEXT_PUBLIC_URL.startsWith("http")
        ? process.env.NEXT_PUBLIC_URL.replace(/\/+$/, "")
        : "http://localhost:3000";

    const imageUrl = `${base}/api/map-image?fid=${encodeURIComponent(
      String(fid)
    )}&mode=both&w=1000&h=1000&v=${Date.now()}`;

    const imgRes = await fetch(imageUrl, { cache: "no-store" });
    if (!imgRes.ok) {
      const t = await imgRes.text();
      return NextResponse.json(
        { error: "Failed to generate image", detail: t.slice(0, 300) },
        { status: 500 }
      );
    }

    const pngBuffer = Buffer.from(await imgRes.arrayBuffer());

    // 2) Init Irys (Base) + force RPC
    const irys = await Uploader(BaseEth)
      .withRpc(mustEnv("BASE_RPC_URL"))
      .withWallet(mustEnv("IRYS_PRIVATE_KEY"));

    const addr = await readIrysAddress(irys);
    let loadedBal = await readLoadedBalance(irys);
    console.log("[irys] address:", addr);
    console.log("[irys] loaded balance:", loadedBal.toString());

    // 3) Estimate cost
    const pngPrice = toBigInt(await irys.getPrice(pngBuffer.length));

    const metaEstimate = {
      name: `Far Map #${fid}`,
      description: "A map of your Farcaster network generated by Far Maps.",
      image: "https://gateway.irys.xyz/<txid>",
      external_url: "https://far-maps.vercel.app",
      attributes: [
        { trait_type: "FID", value: fid },
        ...(username ? [{ trait_type: "Username", value: username }] : []),
      ],
    };

    const metaBytes = Buffer.byteLength(JSON.stringify(metaEstimate), "utf8");
    const metaPrice = toBigInt(await irys.getPrice(metaBytes));

    const numerator = pngPrice + metaPrice;
    const totalNeeded = (numerator * BigInt(110)) / BigInt(100);

    // 4) Auto-fund if needed
    if (loadedBal < totalNeeded) {
      const toFund = totalNeeded - loadedBal;
      console.log("[irys] funding:", toFund.toString());

      const fundRes = await irys.fund(toFund);
      console.log("[irys] fund tx:", fundRes?.id ?? fundRes);

      loadedBal = await readLoadedBalance(irys);
      console.log("[irys] balance after fund:", loadedBal.toString());
    }

    // 5) Upload PNG
    const imgReceipt = await irys.upload(pngBuffer, {
      tags: [
        { name: "Content-Type", value: "image/png" },
        { name: "App-Name", value: "FarMaps" },
        { name: "Type", value: "Farmap" },
        { name: "FID", value: String(fid) },
        ...(username ? [{ name: "Username", value: username }] : []),
      ],
    });

    const imgUrls = gatewaysFor(imgReceipt.id);

    // 6) Upload metadata
    const metadata = {
      name: `Far Map #${fid}`,
      description: "A map of your Farcaster network generated by Far Maps.",
      imageUrl: imgUrls.arweaveNet,
      external_url: "https://far-maps.vercel.app",
      attributes: [
        { trait_type: "FID", value: fid },
        ...(username ? [{ trait_type: "Username", value: username }] : []),
      ],
    };

    const metaReceipt = await irys.upload(JSON.stringify(metadata), {
      tags: [
        { name: "Content-Type", value: "application/json" },
        { name: "App-Name", value: "FarMaps" },
        { name: "Type", value: "Metadata" },
        { name: "FID", value: String(fid) },
        ...(username ? [{ name: "Username", value: username }] : []),
      ],
    });

    const metaUrls = gatewaysFor(metaReceipt.id);

    return NextResponse.json({
      ok: true,
      fid,
      username,
      imageUrl: imgUrls.arweaveNet,
      tokenUri: metaUrls.arweaveNet,
      imgTx: imgReceipt.id,
      metaTx: metaReceipt.id,
      imageUrls: imgUrls,
      tokenUriUrls: metaUrls,
    });
  } catch (e: any) {
    console.error("mint/prepare error:", e);
    return NextResponse.json(
      {
        error: e?.message || "Server error",
        detail: String(e?.stack || "").slice(0, 2000),
      },
      { status: 500 }
    );
  }
}
