export const runtime = "nodejs";

import { NextResponse } from "next/server";
import { Uploader } from "@irys/upload";
import { BaseEth } from "@irys/upload-ethereum";

function mustEnv(name: string) {
  const v = process.env[name];
  if (!v) throw new Error(`Missing env var: ${name}`);
  return v;
}

type PrepareBody = { fid: number };

function gatewaysFor(id: string) {
  return {
    irysGateway: `https://gateway.irys.xyz/${id}`,
    irysNode1: `https://node1.irys.xyz/${id}`,
    irysNode2: `https://node2.irys.xyz/${id}`,
    // These MAY work later (or never) depending on how/when it lands on Arweave gateways:
    arweaveNet: `https://arweave.net/${id}`,
    arIo: `https://ar-io.dev/${id}`,
  };
}

export async function POST(req: Request) {
  try {
    const body = (await req.json()) as PrepareBody;
    const fid = Number(body?.fid);

    if (!Number.isFinite(fid) || fid <= 0) {
      return NextResponse.json({ error: "Missing or invalid fid" }, { status: 400 });
    }

    // 1) Fetch the PNG from your existing generator
    const base =
      process.env.NEXT_PUBLIC_URL && process.env.NEXT_PUBLIC_URL.startsWith("http")
        ? process.env.NEXT_PUBLIC_URL.replace(/\/+$/, "")
        : "http://localhost:3000";

    const imageUrl = `${base}/api/map-image?fid=${encodeURIComponent(
      String(fid)
    )}&mode=both&w=1000&h=1000&v=${Date.now()}`;

    const imgRes = await fetch(imageUrl, { cache: "no-store" });
    if (!imgRes.ok) {
      const t = await imgRes.text();
      return NextResponse.json({ error: "Failed to generate image", detail: t.slice(0, 300) }, { status: 500 });
    }

    const pngBuffer = Buffer.from(await imgRes.arrayBuffer());

    // 2) Init Irys uploader (Base)
    const pk = mustEnv("IRYS_PRIVATE_KEY");
    const irys = await Uploader(BaseEth).withWallet(pk);

    // 3) Upload PNG
    const imgReceipt = await irys.upload(pngBuffer, {
      tags: [
        { name: "Content-Type", value: "image/png" },
        { name: "App-Name", value: "FarMaps" },
        { name: "Type", value: "Farmap" },
        { name: "FID", value: String(fid) },
      ],
    });

    const imgUrls = gatewaysFor(imgReceipt.id);

    // 4) Upload metadata JSON (tokenURI)
    const metadata = {
      name: `Far Map #${fid}`,
      description: "A map of your Farcaster network generated by Far Maps.",
      // Use the Irys gateway URL by default (fastest / intended for Irys receipts)
      image: imgUrls.irysGateway,
      external_url: "https://far-maps.vercel.app",
      attributes: [{ trait_type: "FID", value: fid }],
    };

    const metaReceipt = await irys.upload(JSON.stringify(metadata), {
      tags: [
        { name: "Content-Type", value: "application/json" },
        { name: "App-Name", value: "FarMaps" },
        { name: "Type", value: "Metadata" },
        { name: "FID", value: String(fid) },
      ],
    });

    const metaUrls = gatewaysFor(metaReceipt.id);

    return NextResponse.json({
      ok: true,
      fid,

      // Keep old fields for compatibility:
      imageUrl: imgUrls.irysGateway,
      tokenUri: metaUrls.irysGateway,

      imgTx: imgReceipt.id,
      metaTx: metaReceipt.id,

      // New: multiple gateway options so you can see what works on your network
      imageUrls: imgUrls,
      tokenUriUrls: metaUrls,
    });
  } catch (e: any) {
    console.error("mint/prepare error:", e);
    return NextResponse.json(
      { error: e?.message || "Server error", detail: String(e?.stack || "").slice(0, 2000) },
      { status: 500 }
    );
  }
}
